# Generated by Django 4.0.5 on 2022-06-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_pontuacaoquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadeiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=6)),
                ('semestre', models.CharField(max_length=6)),
                ('anoLetivo', models.CharField(max_length=12)),
                ('descricao', models.CharField(max_length=500)),
                ('projecto', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
