# Generated by Django 4.0.5 on 2022-06-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cadeiras_alter_post_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadeiras',
            new_name='cadeira',
        ),
    ]
