# Generated by Django 4.0.5 on 2022-06-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_cadeiras_cadeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='semestre',
            field=models.CharField(max_length=20),
        ),
    ]
