# Generated by Django 4.0.5 on 2022-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_cadeira_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='ects',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
