# Generated by Django 4.0.5 on 2022-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_cadeira_ects'),
    ]

    operations = [
        migrations.CreateModel(
            name='projecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.CharField(max_length=500)),
                ('github', models.URLField(blank=True)),
            ],
        ),
    ]
