# Generated by Django 4.0.5 on 2022-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_projecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='pictures/')),
            ],
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projecto',
            name='imagem',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
